apiVersion: v1
name: nodeexporter
version: 8.15.0
appVersion: 2.11.1
description: NodeExporter description.
home: https://prometheus.io/
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
sources:
  - https://github.com/prometheus/node_exporter
maintainers:
  - name: mgoodness
    email: mgoodness@gmail.com
  - name: gianrubio
    email: gianrubio@gmail.com
engine: gotpl
tillerVersion: ">=2.8.0"
